### Customer Service API
# @name Customer
POST localhost:8184/customers
Content-Type: application/json

{
  "customerId": "d215b5f8-0249-4dc5-89a3-51fd148cfb41",
  "username": "lguser1",
  "firstName": "lg1",
  "lastName": "lg1"
}

### Scenario 1: Happy Path
# @name Happy Path
POST localhost:8181/orders
Content-Type: application/json

{
  "customerId": "d215b5f8-0249-4dc5-89a3-51fd148cfb41",
  "restaurantId": "d215b5f8-0249-4dc5-89a3-51fd148cfb45",
  "address": {
    "street": "street_1",
    "postalCode": "1000AB",
    "city": "Amsterdam"
  },
  "price": 200.00,
  "items": [
    {
      "productId": "d215b5f8-0249-4dc5-89a3-51fd148cfb48",
      "quantity": 1,
      "price": 50.00,
      "subTotal": 50.00
    },
    {
      "productId": "d215b5f8-0249-4dc5-89a3-51fd148cfb48",
      "quantity": 3,
      "price": 50.00,
      "subTotal": 150.00
    }
  ]
}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body["orderTrackingId"] != null, "Response message is not valid");
        client.global.set("orderTrackingId", response.body.orderTrackingId);
    });
%}

### Scenario 2: Product unavailable
# @name  Product unavailable
POST localhost:8181/orders
Content-Type: application/json

{
  "customerId": "d215b5f8-0249-4dc5-89a3-51fd148cfb41",
  "restaurantId": "d215b5f8-0249-4dc5-89a3-51fd148cfb45",
  "address": {
    "street": "street_1",
    "postalCode": "1000AB",
    "city": "Amsterdam"
  },
  "price": 25.00,
  "items": [
    {
      "productId": "d215b5f8-0249-4dc5-89a3-51fd148cfb47",
      "quantity": 1,
      "price": 25.00,
      "subTotal": 25.00
    }
  ]
}

> {%
    client.global.set("orderTrackingId", response.body.orderTrackingId);
%}

### Scenario 2: insufficient credit
# @name  insufficient credit
POST localhost:8181/orders
Content-Type: application/json

{
  "customerId": "d215b5f8-0249-4dc5-89a3-51fd148cfb41",
  "restaurantId": "d215b5f8-0249-4dc5-89a3-51fd148cfb45",
  "address": {
    "street": "street_1",
    "postalCode": "1000AB",
    "city": "Amsterdam"
  },
  "price": 550.00,
  "items": [
    {
      "productId": "d215b5f8-0249-4dc5-89a3-51fd148cfb48",
      "quantity": 1,
      "price": 50.00,
      "subTotal": 50.00
    },
    {
      "productId": "d215b5f8-0249-4dc5-89a3-51fd148cfb48",
      "quantity": 10,
      "price": 50.00,
      "subTotal": 500.00
    }
  ]
}

> {%
    client.global.set("orderTrackingId", response.body.orderTrackingId);
%}

### Get Order satus
# @name Tracking
GET localhost:8181/orders/{{orderTrackingId}}
